### ISSUE TITLE
Don't perform side effects in update.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [bcpeinhardt/squared_away#1]
In Lustre, one of the core principles is that your `update` are `view` functions are _pure_ and side effects are wrapped up in an `Effect` to be managed by the runtime.

Currently you're violating that principle by interacting with the DOM directly inside your `update` function:

https://github.com/bcpeinhardt/squared_away/blob/40eb013ec52e5994d194afd04f0bf578fefb29ea/src/squared_away.gleam#L212

Instead consider doing:

```gleam
@external(javascript, "./squared_away_ffi.js", "focus")
fn do_focus(_id: String) -> Nil {
  Nil
}

fn focus(id: String) -> Effect(msg) {
  use _ <- effect.from
  focus(id)
}
```

and returning this `focus` effect in any branches of your update function that need it.

## Why do we do this?

There's a page in the guide about managed side effects in Lustre that would be valuable to read: https://github.com/lustre-labs/lustre/blob/main/pages/guide/03-side-effects.md

Some of the main benefits you will see are:

- You can now write `gleeunit` tests for your `update` function. 
- You could run your update function on the server for prerendering.
- You could consider using squared_away as a server component in the future without refactoring anything.

**Comment by bcpeinhardt** [comment]
Done :)
