### ISSUE TITLE
Move key handling logic into event handlers.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [bcpeinhardt/squared_away#2]
Currently you have a couple of message variants that only perform meaningful work when certain keys are pressed, and others are ignored and you return `#(model, effect.none())`:

https://github.com/bcpeinhardt/squared_away/blob/40eb013ec52e5994d194afd04f0bf578fefb29ea/src/squared_away.gleam#L130

Instead of doing this you can simplify your code _and_ get additional guarantees around your `Msg` type if you move this logic into a custom event handler.

```gleam
let on_keydown = fn(event) {
  use key <- result.try(dynamic.field("key", dynamic.string)(event))
  use shift <- result.try(dynamic.field("shiftKey", dynamic.bool)(event))

  case key {
    "ArrowUp" -> Ok(UserPressedArrowUp(cell))
    "ArrowLeft" -> Ok(UserPressedArrowLeft(cell))
    "ArrowRight" if shift -> Ok(UserPressedShiftArrowRight(cell))
    ...

    // Returning an empty error here means no message is dispatched at all.
    _ -> Error([])
  }
}
```

You can seem some examples of this in Lustre/ui's combobox: https://github.com/lustre-labs/ui/blob/b114b6949479ebf03f5ec0eb1d5af31a3ab918b1/src/lustre/ui/combobox.gleam#L504

You'll also notice I'm handling the "is shift held" logic in the event handler here, so you can remove tracking that state in the model all together.

By doing it this way your `Msg` type gets way more precise, so it's clearer for everyone when they look at it what the scope of interaction in your app is _and_ our update function got simpler to boot!

**Comment by bcpeinhardt** [comment]
Done :) so much better thank you
